force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <description>Our Customers</description>
    <label>People</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Members</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of pet</description>
    <formula>IF( NOT( ISBLANK( Birthdate__c ) ) ,
  IF( DATE( 2000 , MONTH( Birthdate__c ) , DAY( Birthdate__c ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Birthdate__c ),
     YEAR (Today()) - YEAR ( Birthdate__c ) -1 ),
  null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Birthdate of pet</description>
    <inlineHelpText>Enter the birthdate of the pet.</inlineHelpText>
    <label>Birthdate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <description>Shows Birthday cake image on pet&#39;s birthday.</description>
    <formula>IF(AND(MONTH(Birthdate__c) = MONTH(TODAY()), DAY(Birthdate__c) = DAY(TODAY())), IMAGE(&quot;https://abcpets2-dev-ed--c.documentforce.com/servlet/servlet.FileDownload?file=0155Y0000056sse&quot;, &quot;Birthday Cake&quot;, 30, 30),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Shows Birthday cake image on pet&#39;s birthday.</inlineHelpText>
    <label>Birthday</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>Breed of pet</description>
    <inlineHelpText>Optional - Enter the breed of the pet.</inlineHelpText>
    <label>Breed</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Pet_Owner__c.field-meta.xml
<CustomField>
    <fullName>Pet_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Pet</description>
    <inlineHelpText>Select the type of pet.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dog</fullName>
            </value>
            <value>
                <fullName>Cat</fullName>
            </value>
            <value>
                <fullName>Bird</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Rabbit</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>Snake</fullName>
            </value>
            <value>
                <fullName>Lizard</fullName>
            </value>
            <value>
                <fullName>Hamster</fullName>
            </value>
            <value>
                <fullName>Guinea Pig</fullName>
            </value>
            <value>
                <fullName>Mouse</fullName>
            </value>
            <value>
                <fullName>Rat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Pets/Pet_List_Controller.cls
public  class Pet_List_Controller 
{
    @AuraEnabled (cacheable=true)
    public static List<Pet_Data_Wrapper> getPets(Id recordId)
    {

        String familyId;
        List<Pet_Data_Wrapper> pets = new List<Pet_Data_Wrapper>();
        String objectType = recordId.getSObjectType().getDescribe().getName();

        switch on objectType
        {
            when 'People__c'
            {
                Map<Id, Id> mapFamilyIds = People_Query_Layer.getFamilyIdsForPets(new List<Id>{recordId});
                if (!mapFamilyIds.isEmpty() && mapFamilyIds.containsKey(recordId))
                {
                    familyId = mapFamilyIds.get(recordId);
                }
            }
            when 'Family__c'
            {
                familyId = recordId;
            }
        }

        if (String.isNotBlank(familyId))
        {
            for (Pet__c p : Pet_Query_Layer.getPetsByFamilyId(familyId))
            {
                Pet_Data_Wrapper pet = new Pet_Data_Wrapper();
                pet.petId = p.Id;
                pet.petURL = '/' + p.Id;
                pet.name = p.Name;
                pet.ownerURL = '/' + p.Pet_Owner__c;
                pet.owner = p.Pet_Owner__r.Name;
                pet.type = p.Type__c;
                pet.breed = p.Breed__c;
                pet.age = String.valueOf(p.Age__c);
                pet.birthdate = p.Birthdate__c;
                pet.birthday = p.Birthday__c;
                pets.add(pet);
            }
        }

        return pets;
    }    
}