force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <description>Our Customers</description>
    <label>People</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Members</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Family/Family_Query_Layer.cls
public class Family_Query_Layer 
{
    public static Map<Id, List<People__c>> getFamilyMembers(List<Id> familyIds)
    {
        Map<Id, List<People__c>> mapFamilyMembers = new Map<Id, List<People__c>>();
        for (Family__c f : [Select Id, (SELECT Id From People__r) From Family__c WHERE ID IN :familyIds])
        {
            mapFamilyMembers.put(f.Id, f.People__r);
        }
        return mapFamilyMembers;
    }
}