force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <description>Our Customers</description>
    <label>People</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Customer&#39;s email address</description>
    <inlineHelpText>Please enter the customer&#39;s email address.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/People__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Members</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <description>Customer&#39;s mailing address</description>
    <inlineHelpText>Please enter the customer&#39;s mailing address.</inlineHelpText>
    <label>Mailing Address</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <description>Customer&#39;s Mailing City</description>
    <inlineHelpText>Please enter the customer&#39;s mailing city.</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <description>Customer&#39;s Mailing State</description>
    <inlineHelpText>Please enter the customer&#39;s mailing state.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <description>Customer&#39;s Mailing Zip Code</description>
    <inlineHelpText>Please enter the customer&#39;s mailing zip code.</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <description>Customer&#39;s primary phone number</description>
    <inlineHelpText>Please enter the customer&#39;s primary phone number.</inlineHelpText>
    <label>Primary Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/People/People_Query_Layer_Tests.cls
@isTest
public class People_Query_Layer_Tests
{
    @TestSetup
    static void makeData()
    {
        Test.startTest();
        
        Family__c f = new Family__c();
        f.Name = 'Test Family';
        insert f;

        People__c p= new People__c();
        p.Family__c = f.Id;
        p.Name = 'Test Person';
        p.Email__c = 'test.person@demo.biz';
        p.Primary_Phone__c = '1234567890';
        p.Mailing_Address__c = '123 Test Dr';
        p.Mailing_City__c = 'Somewhere';
        p.Mailing_State__c = 'NJ';
        p.Mailing_Zip_Code__c = '12345';
        insert p;

        Test.stopTest();        
    }

    @isTest static void test_getFamilyIdsForPets_Positive()
    {
        People__c p = [SELECT Id, Family__c FROM People__c WHERE Email__c = 'test.person@demo.biz'];
        Family__c f = [SELECT Id From Family__c WHERE ID = :p.Family__c];

        Test.startTest();
        Map<Id, Id> results = People_Query_Layer.getFamilyIdsForPets(new List<Id>{p.Id});
        Test.stopTest();

        System.assert(!results.isEmpty());
        System.assert(results.containsKey(p.Id));
        System.assertEquals(f.Id, results.get(p.Id));
    }

    @isTest static void test_getFamilyMembers_Negative()
    {
        List<Id> peopleIds = new List<Id>();

        Test.startTest();
        Map<Id, Id> results = People_Query_Layer.getFamilyIdsForPets(peopleIds);
        Test.stopTest();

        System.assert(results.isEmpty());
    }
}