force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <description>Our Customers</description>
    <label>People</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Members</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/People/People_Query_Layer.cls
public class People_Query_Layer 
{
    public static Map<Id, Id> getFamilyIdsForPets(List<Id> ownerIds)
    {
        Map<Id, Id> familyIds = new Map<Id, Id>();
        for (People__c p : [SELECT Id, Family__c  FROM People__c WHERE Id IN :ownerIds])
        {
            if (String.isNotBlank(p.Family__c))
            {
                familyIds.put(p.Id,p.Family__c);
            }
        }
        
        return familyIds;
    }
}