force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <description>Our Customers</description>
    <label>People</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/People__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Customer&#39;s email address</description>
    <inlineHelpText>Please enter the customer&#39;s email address.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/People__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Members</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <description>Customer&#39;s mailing address</description>
    <inlineHelpText>Please enter the customer&#39;s mailing address.</inlineHelpText>
    <label>Mailing Address</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <description>Customer&#39;s Mailing City</description>
    <inlineHelpText>Please enter the customer&#39;s mailing city.</inlineHelpText>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <description>Customer&#39;s Mailing State</description>
    <inlineHelpText>Please enter the customer&#39;s mailing state.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <description>Customer&#39;s Mailing Zip Code</description>
    <inlineHelpText>Please enter the customer&#39;s mailing zip code.</inlineHelpText>
    <label>Zip Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/People__c/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <description>Customer&#39;s primary phone number</description>
    <inlineHelpText>Please enter the customer&#39;s primary phone number.</inlineHelpText>
    <label>Primary Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>Birthdate of pet</description>
    <inlineHelpText>Enter the birthdate of the pet.</inlineHelpText>
    <label>Birthdate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Family Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Pet_Owner__c.field-meta.xml
<CustomField>
    <fullName>Pet_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Pet</description>
    <inlineHelpText>Select the type of pet.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dog</fullName>
            </value>
            <value>
                <fullName>Cat</fullName>
            </value>
            <value>
                <fullName>Bird</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Rabbit</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>Snake</fullName>
            </value>
            <value>
                <fullName>Lizard</fullName>
            </value>
            <value>
                <fullName>Hamster</fullName>
            </value>
            <value>
                <fullName>Guinea Pig</fullName>
            </value>
            <value>
                <fullName>Mouse</fullName>
            </value>
            <value>
                <fullName>Rat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL-{00000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/People__c.field-meta.xml
<CustomField>
    <fullName>People__c</fullName>
    <label>People</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Related Pets</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Related People</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation To Pet</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Caretaker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Pets/Pet_Trigger_Tests.cls
@isTest
public class Pet_Trigger_Tests 
{
    @TestSetup
    static void makeData()
    {
        Test.startTest();
        
        Family__c f = new Family__c();
        f.Name = 'Test Family';
        insert f;

        People__c p= new People__c();
        p.Family__c = f.Id;
        p.Name = 'Test Person';
        p.Email__c = 'test.person@demo.biz';
        p.Primary_Phone__c = '1234567890';
        p.Mailing_Address__c = '123 Test Dr';
        p.Mailing_City__c = 'Somewhere';
        p.Mailing_State__c = 'NJ';
        p.Mailing_Zip_Code__c = '12345';
        insert p;

        Pet__c pet = new Pet__c();
        pet.Name = 'Test';
        pet.Birthdate__c = Date.today().addYears(-6);
        pet.Type__c = 'Dog';
        pet.Pet_Owner__c = p.Id;
        pet.Family__c = f.Id;
        insert pet;

        Test.stopTest();
    }

    @isTest static void test_relatePetsToFamilyMembers_Positive()
    {
        People__c person = [SELECT Id, Family__c FROM People__c WHERE Email__c = 'test.person@demo.biz'];

        Test.startTest();

        People__c p= new People__c();
        p.Family__c = person.Family__c;
        p.Name = 'Pet Owner';
        p.Email__c = 'pet.owner@demo.biz';
        p.Primary_Phone__c = '1234567890';
        p.Mailing_Address__c = '123 Test Dr';
        p.Mailing_City__c = 'Somewhere';
        p.Mailing_State__c = 'NJ';
        p.Mailing_Zip_Code__c = '12345';
        insert p;
        
        Pet__c pet = new Pet__c();
        pet.Name = 'Rex';
        pet.Birthdate__c = Date.today().addYears(-6);
        pet.Type__c = 'Hamster';
        pet.Pet_Owner__c = p.Id;
        insert pet;

        Test.stopTest();

        List<Id> petIds = new List<Id>{pet.Id};
        List<Id> peopleIds = new List<Id>{person.Id, p.Id};
        List<Relationship__c> results = [SELECT Id, Pet__c, People__c, Relation__c FROM Relationship__c WHERE Pet__c IN : petIds AND People__c IN :peopleIds];
        System.assert(!results.isEmpty());
        for (Relationship__c r : results)
        {
            System.assertEquals(pet.Id, r.Pet__c);
            if (r.People__c == person.Id) System.assertEquals('Family Member', r.Relation__c);
            if (r.People__c == p.Id) System.assertEquals('Owner', r.Relation__c);
        }
    }

    @isTest static void test_relatePetsToFamilyMembers_Negative()
    {
        Test.startTest();

        Pet__c pet = new Pet__c();
        pet.Name = 'Rex';
        pet.Birthdate__c = Date.today().addYears(-6);
        pet.Type__c = 'Hamster';
        insert pet;

        Test.stopTest();

        List<Id> petIds = new List<Id>{pet.Id};
        List<Relationship__c> results = [SELECT Id, Pet__c, People__c, Relation__c FROM Relationship__c WHERE Pet__c IN : petIds];
        System.assert(results.isEmpty());
    }

    @isTest static void test_relatePetsToFamilyMembers_Exception()
    {
        Test.startTest();

        Family__c f = new Family__c();
        f.Name = 'Exception Family';
        insert f;

        People__c p= new People__c();
        p.Family__c = f.Id;
        p.Name = 'Pet Owner';
        p.Email__c = 'pet.owner@demo.biz';
        p.Primary_Phone__c = '1234567890';
        p.Mailing_Address__c = '123 Test Dr';
        p.Mailing_City__c = 'Somewhere';
        p.Mailing_State__c = 'NJ';
        p.Mailing_Zip_Code__c = '12345';
        insert p;
        
        Pet__c pet = new Pet__c();
        pet.Name = 'Exception Handling Test';
        pet.Birthdate__c = Date.today().addYears(-6);
        pet.Type__c = 'Hamster';
        pet.Pet_Owner__c = p.Id;
        insert pet;

        Test.stopTest();

        List<Id> petIds = new List<Id>{pet.Id};
        List<Id> peopleIds = new List<Id>{p.Id};
        List<Relationship__c> results = [SELECT Id, Pet__c, People__c, Relation__c FROM Relationship__c WHERE Pet__c IN : petIds AND People__c IN :peopleIds];
        System.assert(results.isEmpty());
    }
}