force-app/main/default/objects/People__c/People__c.object-meta.xml
<CustomObject>
    <description>Our Customers</description>
    <label>People</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Pet_Owner__c.field-meta.xml
<CustomField>
    <fullName>Pet_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL-{00000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/People__c.field-meta.xml
<CustomField>
    <fullName>People__c</fullName>
    <label>People</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Related Pets</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Related People</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relation__c.field-meta.xml
<CustomField>
    <fullName>Relation__c</fullName>
    <label>Relation To Pet</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Family Member</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Caretaker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Pets/Pet_Trigger_Helper.cls
public class Pet_Trigger_Helper 
{
    public static void relatePetsToFamilyMembers(Map<Id, Pet__c> newPets)
    {
        List<Relationship__c> relationshipsToInsert = new List<Relationship__c>();
        Map<Id, Id> mapOwnersFamilyIds = People_Query_Layer.getFamilyIdsForPets(new List<Id>(newPets.keySet()));
        Map<Id, List<People__c>> mapFamilyMembers = Family_Query_Layer.getFamilyMembers(mapOwnersFamilyIds.values());

        for (Pet__c pet : newPets.values())
        {
            Id ownerId = pet.Pet_Owner__c;
            if (mapOwnersFamilyIds.containsKey(ownerId))
            {
                Id familyId = mapOwnersFamilyIds.get(ownerId);

                for (People__c familyMember : mapFamilyMembers.get(familyId))
                {
                    Relationship__c r = new Relationship__c();
                    r.Pet__c = pet.Id;
                    r.People__c = familyMember.Id;
                    r.Relation__c = pet.Pet_Owner__c == familyMember.Id ? 'Owner' : 'Family Member';
                    relationshipsToInsert.add(r);
                }
            }
        }

        if (!relationshipsToInsert.isEmpty())
        {
            if (Test.isRunningTest() && newPets.values()[0].Name == 'Exception Handling Test') relationshipsToInsert[0].Pet__c = null;

            Database.SaveResult[] srList = Database.insert(relationshipsToInsert, false);

            for(Database.SaveResult sr : srList)
            {
                if (!sr.isSuccess())
                {
                    for (Database.Error err : sr.getErrors()) 
                    {
                        System.debug('Failed to insert relationship' + err.getMessage() + ' Fields that affected this error: ' + err.getFields());
                    }
                }
            }
        }
    }
}