force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <label>Pet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Pet_Owner__c.field-meta.xml
<CustomField>
    <fullName>Pet_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>People__c</referenceTo>
    <relationshipLabel>Pets</relationshipLabel>
    <relationshipName>Pets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Pets/Pet_Trigger_Utility.cls
public class Pet_Trigger_Utility 
{
    public static void AfterInsert(List<Pet__c> newPets)
    {
        Map<Id, Pet__c> mapPetsToRelate = new Map<Id, Pet__c>();

        for (Pet__c p : newPets)
        {
            if (String.isNotBlank(p.Pet_Owner__c))
            {
                mapPetsToRelate.put(p.Pet_Owner__c, p);
            }
        }

        if (!mapPetsToRelate.isEmpty()) Pet_Trigger_Helper.relatePetsToFamilyMembers(mapPetsToRelate);      
    }
}